### ISSUE TITLE
Support osu! lazer scrobbling

### ISSUE THREAD

**Issue by eepytofu** [flazepe/osu-scrobbler#1]
Great work! Any plans for osu! lazer scrobbling?

**Comment by flazepe** [comment]
Thank you! I've been thinking about this. Since osu!lazer does not change the window title whenever a new beatmap is playing, the only solutions are:

1. Create an issue or PR on the osu!lazer repo to support it (this might work since it might've been overlooked).
2. Read the process memory instead to get current beatmap info (this was what I wanted to do for this project, but I thought it was too complicated for a simple project like this so I check the window title instead since they're perfect for this use case). This however would remove the need for beatmap mirrors since all the data would be available locally.

**Comment by Gersonzao** [comment]
Wouldn't it be possible to use osu!'s API? I *think* [this](https://github.com/ppy/osu-api/wiki#scores) might help

**Comment by flazepe** [comment]
> Wouldn't it be possible to use osu!'s API? I _think_ [this](https://github.com/ppy/osu-api/wiki#scores) might help

Oh my god, I've never thought about using the recents API. You're a genius! I believe I was too focused on thinking about the "now playing" part that it went completely over my mind (and I haven't even implemented the now playing feature yet!).

I'll use the new API though, as API v1 is legacy at this point. I'll report back whenever I could get it done.

**Comment by flazepe** [comment]
@EternalDesire @Gersonzao The newest release now supports osu! and osu!lazer with the use of osu! API!

Here are the steps to update:

- Rename the `scrobble` section in your config file to `scrobbler`
- Add the `user_id` field with your osu! user ID in the same section
- This is optional, but you can also provide the `mode` field under the same section (supported values are `osu`, `taiko`, `fruits`, and `mania`) if you want to scrobble a mode that's different than your derfault mode

**Comment by g1-1-1** [comment]
why not implement this into lazer itself?
